name: geocat-examples
channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - geocat-datafiles
  - geocat-viz=2020.7.30.1
  - netcdf4
  - cartopy
  - scikit-learn
  - mock
  - pillow
  - scikit-learn
  - sphinx
  - matplotlib=3.3.0
  - sphinx-gallery
  - sphinx_rtd_theme
  - jupyter
  - make
  - geographiclib
<<<<<<< HEAD
=======
  - wrf-python
>>>>>>> dfea5716a8710f67f53ca62a329a4ce3ba3452e0
  - metpy
