name: actions
on: 
  push:
    branches-ignore:
      - master
      - develop
    tags-ignore:
      - yapf
jobs:
  yapf_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.AKOOTZ_TOKEN }}
      - name: yapf
        run: |
          pip3 install yapf
          python3 -m yapf --in-place --recursive --style google .
      - name: push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'
          git tag yapf
          git commit --allow-empty -am "yapf google style formatting, pushed by github action"
          git push
