name: Build documentation pages

on:
  push:
    branches:
    - '*'
  pull_request_target:
    branches:
    - '*'

jobs:
  build-and-run:
    name: Build documentation pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create conda environment
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      uses: goanpeca/setup-miniconda@v1
      with:
         activate-environment: geocat-examples
         environment-file: conda_environment.yml
    - name: Build sphinx docs
      shell: bash -l {0}
      run: |
        conda info
        conda list
        make html
