name: CI Nightly
on:
  workflow_dispatch:
  schedule:
  - cron: '0 1 * * *' # Daily “At 01:00”

jobs:
  build-and-run:
    name: Build Sphinx Docs (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "macos-latest"]
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v3
    - name: Create conda environment
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      uses: mamba-org/provision-with-micromamba@main
      with:
         micromamba-version: "latest"
         environment-name: geocat-examples
         environment-file: conda_environment.yml
    - name: Make html
      shell: bash -l {0}
      working-directory: ./docs
      run: |
        conda info
        conda list
        make html
