name: CI Upstream
on:
  schedule:
    - cron: "0 0 * * 0" # daily at 00:00 UTC
  workflow_dispatch: # allows you to trigger the workflow run manually

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upstream-dev:
    name: upstream-dev
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches and tags.
      - name: set up environment
        uses: mamba-org/setup-micromamba@0dea6379afdaffa5d528b3d1dabc45da37f443fc # v2.0.4
        with:
          environment-file: conda_environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
      - name: install upstream versions
        run: |
          bash ci/install-upstream.sh
      - name: environment info
        run: |
          conda info
          conda list
      - name: make html
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
           timeout_minutes: 20
           max_attempts: 3
           command: |
              eval "$(micromamba shell hook --shell bash)"
              micromamba activate
              micromamba activate geocat-examples
              cd docs
              make html
